package com.shengx1ao.entity;

import tk.mybatis.mapper.common.Mapper;

import javax.persistence.*;

/**
 * Database Table Remarks:
 *   订单商品关系映射表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order_goods
 */
@Table(name="order_goods")
public class OrderGoods {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Database Column Remarks:
     *   所属订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.orderId
     *
     * @mbg.generated
     */
    @Column(name="orderId")
    private Long orderid;

    /**
     * Database Column Remarks:
     *   所属商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.goodsId
     *
     * @mbg.generated
     */
    @Column(name="goodsId")
    private Long goodsid;

    /**
     * Database Column Remarks:
     *   商品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.count
     *
     * @mbg.generated
     */
    @Column(name="count")
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.id
     *
     * @return the value of order_goods.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.id
     *
     * @param id the value for order_goods.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.orderId
     *
     * @return the value of order_goods.orderId
     *
     * @mbg.generated
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.orderId
     *
     * @param orderid the value for order_goods.orderId
     *
     * @mbg.generated
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.goodsId
     *
     * @return the value of order_goods.goodsId
     *
     * @mbg.generated
     */
    public Long getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.goodsId
     *
     * @param goodsid the value for order_goods.goodsId
     *
     * @mbg.generated
     */
    public void setGoodsid(Long goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.count
     *
     * @return the value of order_goods.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.count
     *
     * @param count the value for order_goods.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}